/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecisionRoomRouteImport } from './routes/decision-room'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OverviewRouteImport } from './routes/overview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoomRoute = DecisionRoomRouteImport.update({
  id: '/decision-room',
  path: '/decision-room',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decision-room': typeof DecisionRoomRoute
  '/inventory': typeof InventoryRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decision-room': typeof DecisionRoomRoute
  '/inventory': typeof InventoryRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decision-room': typeof DecisionRoomRoute
  '/inventory': typeof InventoryRoute
  '/overview': typeof OverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decision-room' | '/inventory' | '/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decision-room' | '/inventory' | '/overview'
  id: '__root__' | '/' | '/decision-room' | '/inventory' | '/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionRoomRoute: typeof DecisionRoomRoute
  InventoryRoute: typeof InventoryRoute
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-room': {
      id: '/decision-room'
      path: '/decision-room'
      fullPath: '/decision-room'
      preLoaderRoute: typeof DecisionRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionRoomRoute: DecisionRoomRoute,
  InventoryRoute: InventoryRoute,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
